name: domex
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  uuid: ^4.5.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.4
  pdf: ^3.11.3
  printing: ^5.14.2
  
  # --- Dependências do Firebase ---
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2

  # --- Dependências de Funcionalidades ---
  image_picker: ^1.0.7  # Para tirar foto e pegar da galeria
  url_launcher: ^6.2.5  # Para abrir o link da CNH Digital e WhatsApp
  flutter_notification_listener: ^1.1.0 # Para ler notificações do sistema
  flutter_local_notifications: ^17.0.0 # <--- ADICIONADO: Para enviar o alerta de resultado

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Gerador de ícones
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# --- CONFIGURAÇÃO DOS ÍCONES DO APP ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_icone.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFE5E770"
  adaptive_icon_foreground: "assets/images/logo_icone.png"
  web:
    generate: true
    image_path: "assets/images/logo_icone.png"
    background_color: "#FFE5E770"
    theme_color: "#FFE5E770"